import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "@/components/NavBar";

import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />

      <div className="container mx-auto  px-4">{children}</div>
    </>
  );
}
